export const CV_DATA = {
	personalInfo: {
		fullName: "Javier Ibáñez Vizuete",
		title: "Frontend Developer",
		location: "Madrid, España",
		email: "javieriibanezvizuete@gmail.com",
		linkedin: "https://www.linkedin.com/in/javier-ibanez-vizuete/",
		portfolio: "https://nientiendo-portfolio.netlify.app",
		summary:
			"Desarrollador frontend con experiencia en liderazgo de equipos, optimización de procesos y desarrollo web con tecnologías modernas. Apasionado por la programación y la mejora continua.",
	},
	experiences: [
		{
			position: "Frontend Developer",
			company: "Rocket418",
			period: "Diciembre 2024 - Mayo 2025",
			location: "Madrid, España",
			responsabilities: [
				"Desarrollo de la interfaz de usuario para el proyecto UniformeAzul.com , la academia más grande de España para opositores a la Policía.",
				"Implementación de componentes React reutilizables y rutas con React Router",
				"Gestión del estado global con Redux.js y React Hooks (useState, useEffect).",
				"Creación de formularios dinámicos con React Hook Form y validaciones personalizadas.",
				"Uso de Chakra UI para garantizar un diseño consistente y accesible.",
				"Colaboración con el equipo de diseño y backend para optimizar la experiencia de usuario y mejorar la performance",
			],
		},
		{
			position: "Director",
			company: "Restaurante SAONA",
			period: "oct 2020 - mar 2024",
			location: "Madrid, España",
			responsabilities: [
				"Supervisión de un equipo de 22 personas (camareros y cocineros) en el restaurante SAONA Plaza de España.",
				"Cumplimiento de objetivos de ventas mensuales y generación de incentivos, incrementando el beneficio en un 15 % interanual.",
				"Implementación de controles de costes y gestión de budgets, reduciendo desperdicios y optimizando recursos. ",
				"Coordinación de eventos especiales y promociones, mejorando la satisfacción del cliente y la imagen de marca.",
				"Resolución de incidencias operativas y administrativas, garantizando un servicio fluido y de alta calidad.",
			],
		},
		{
			position: "Supervisor",
			company: "Forge Restaurant & Club",
			period: "sep 2017 - jun 2018",
			location: "Londres, Reino Unido",
			responsabilities: [
				"Liderazgo de personal en restaurante y discoteca, asegurando altos estándares de atención y servicio.",
				"Coordinación de eventos VIP en el Reservado, gestionando protocolo y atención a clientes premium.",
				"Capacitación de camareros nuevos en procedimientos operativos y normas de seguridad alimentaria.",
				"Monitoreo de inventarios y reposición de productos, evitando faltantes en momentos críticos.",
				"Elaboración de reportes semanales de rendimiento y sugerencias de mejora al director de sala.",
			],
		},
	],
	education: [
		{
			degree: "Máster en Programación Web, Inteligencia Artificial y Desarrollo Mobile",
			institution: "Eleven Code School",
			period: "abr 2024 - Actualidad",
		},
	],
	skills: [
		"HTML5",
		"CSS3",
		"JavaScript",
		"React",
		"Redux",
		"Tailwind CSS",
		"Chakra UI",
		"Node.js",
		"Git",
		"Figma",
		"Trello",
		"Jira",
		"Diseño responsivo",
		"UI/UX",
		"Metodologías ágiles",
		"Gestión de equipos",
		"Atención al cliente",
		"Resolución de problemas",
		"Optimización de procesos",
	],
	languages: [
		{ name: "Español", level: "Nativo" },
		{ name: "Inglés", level: "Avanzado (2 años en Reino Unido)" },
	],
	devLanguages: [
		{ name: "JavaScript", level: "Intermedio" },
		{ name: "HTML", level: "Avanzado" },
		{ name: "CSS", level: "Avanzado" },
	],
	technologies: [
		{ name: "React", level: "Intermedio" },
		{ name: "Chakra UI", level: "Intermedio" },
		{ name: "Tailwind CSS", level: "Intermedio" },
		{ name: "Redux", level: "Intermedio" },
		{ name: "Git", level: "Intermedio" },
		{ name: "Node.js", level: "Básico" },
		{ name: "Figma", level: "Intermedio" },
		{ name: "Jira", level: "Intermedio" },
	],
};
