export const INITIAL_MOLE_STATES = [
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
	{ hasMole: false, isSmashed: false },
];
